#!/bin/bash

set -euo pipefail

THIS_DIR=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
ROOT_DIR=$(dirname "${THIS_DIR}")
source ${ROOT_DIR}/utils.sh

if [ -d "${INSTALL_DIR}/awesome-vim" ]; then
    echo "awesome-vim is already installed in ${INSTALL_DIR}/awesome-vim, skipping..."
    # exit 0
else
    echo "Installing awesome-vim in ${INSTALL_DIR}/awesome-vim..."
    git clone --depth=1 https://github.com/amix/vimrc.git ${INSTALL_DIR}/awesome-vim
    touch ${INSTALL_DIR}/awesome-vim/my_configs.vim
fi


echo "
set number
set cursorline
set showmode
" > ${INSTALL_DIR}/awesome-vim/my_configs.vim

# create the .vimrc file in ${ROOT_DIR}/vim/.vimrc
# Note, hardcoded install dir for now, but we can make it more dynamic later if needed
cat > "${ROOT_DIR}/vim/.vimrc" <<EOF
" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.dotfiles/build/awesome-vim/my_configs.vim

set runtimepath+=~/.dotfiles/build/awesome-vim

source ~/.dotfiles/build/awesome-vim/vimrcs/basic.vim
source ~/.dotfiles/build/awesome-vim/vimrcs/filetypes.vim
source ~/.dotfiles/build/awesome-vim/vimrcs/plugins_config.vim
source ~/.dotfiles/build/awesome-vim/vimrcs/extended.vim

try
  source ~/.dotfiles/build/awesome-vim/my_configs.vim
catch
endtry
EOF

echo "✅ Vim configuration has been set up. You can customize it by editing ~/.dotfiles/build/awesome-vim/my_configs.vim"
