FROM ubuntu:latest

ARG USERNAME=user
ARG UID=1000
ARG GID=1000

# install required packages to compile python
RUN set -x \
    && echo "Updating..." \
    && apt-get update \
    && apt-get upgrade -y \
    && echo "Installing Packages..." \
    # wget: download files
    && apt-get install -y wget \
    # git: version control
    && apt-get install -y git \
    # curl: HTTP client
    && apt-get install -y curl \
    # vi: file editing
    && apt-get install -y vim \
    # gcc: C compiler
    && apt-get install -y gcc \
    # make: build tool
    && apt-get install -y make \
    # xz-utils: for .tar.xz extraction
    && apt-get install -y xz-utils \
    # libncurses-dev: required for zsh
    && apt-get install -y libncurses-dev \
    # libncurses-dev: required for zsh
    && apt-get install -y zip \
    # zsh terminal
    && apt-get install -y zsh


RUN if getent group ${GID} >/dev/null; then \
        echo "Group with GID ${GID} already exists, using it."; \
        GROUP_NAME=$(getent group ${GID} | cut -d: -f1); \
    else \
        GROUP_NAME=${USERNAME}; \
        groupadd --gid ${GID} ${GROUP_NAME}; \
    fi && \
    useradd --uid ${UID} --gid ${GID} --create-home --shell /bin/bash ${USERNAME}

WORKDIR /home/${USERNAME}
RUN chown -R ${UID}:${GID} /home/${USERNAME}

USER ${USERNAME}
CMD ["/bin/bash"]
