source "$HOME/.dotfiles/zsh/sources/aliases.sh"
source "$HOME/.dotfiles/zsh/sources/exports.sh"
source "$HOME/.dotfiles/zsh/sources/functions.sh"
source "$HOME/.dotfiles/zsh/sources/pyenv_conf.sh"
source "$HOME/.dotfiles/zsh/sources/ohmyzsh.sh"
